CREATE DATABASE IF NOT EXISTS PalUsers;
CREATE TABLE Users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PlayerID VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    UserID VARCHAR(255) NOT NULL,
    IP VARCHAR(255) NOT NULL,
    last_login DATETIME NOT NULL
);
GRANT ALL PRIVILEGES ON PalUsers.* TO 'palka'@'%' IDENTIFIED BY 'palka';
FLUSH PRIVILEGES;